AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31

Description: >
  Come Follow Me AI Reminder Service

Globals:
  Function:
    Timeout: 60
    Runtime: python3.12
    MemorySize: 256

Resources:

  DailyReminderFunction:
    Type: AWS::Serverless::Function

    Properties:
      FunctionName: cfm-daily-reminder

      CodeUri: .

      Handler: lambda_handler.lambda_handler

      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
          - Effect: Allow
            Action:
              - sns:Publish
              - ssm:GetParameter
              - ssm:GetParameters
            Resource: "*"

      Environment:
        Variables:
          EMAIL_ADDRESS_PARAM: "/cfm/email_address"
          EMAIL_APP_PASSWORD_PARAM: "/cfm/email_app_password"
          EMAIL_RECIPIENTS_PARAM: "/cfm/email_recipients"
          PHONE_NUMBER_PARAM: "/cfm/phone_number"
          GEMINI_API_KEY_PARAM: "/gemini/api_key"
          PYTHONUNBUFFERED: "1"

      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 13 * * ? *)
            Description: Daily Come Follow Me Reminder
            Enabled: true