AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31

Description: >
  Come Follow Me AI Reminder Service

Globals:
  Function:
    Timeout: 60
    Runtime: python3.12
    MemorySize: 256

Resources:

  DailyReminderFunction:
    Type: AWS::Serverless::Function

    Properties:
      FunctionName: cfm-daily-reminder

      CodeUri: .

      Handler: lambda_handler.lambda_handler

      Policies:
        - AWSLambdaBasicExecutionRole
        
        - Statement:
            Effect: Allow
            Action:
              - sns:Publish
            Resource: "*"

        - Statement:
            Effect: Allow
            Action:
              - ssm:GetParameter
            Resource: "*"

      Environment:
        Variables:
          PYTHONUNBUFFERED: "1"

      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 13 * * ? *)
            Description: Daily Come Follow Me Reminder
            Enabled: true